CREATE TABLE IF NOT EXISTS REPORTS(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR NOT NULL,
    subject VARCHAR(50) NOT NULL,
    message VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS EMAILS(
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS USR(
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    active BOOLEAN NOT NULL,
    role VARCHAR NOT NULL
);